# Generated by Django 5.1.4 on 2025-01-13 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('clothesCount', models.IntegerField()),
                ('extras', models.CharField(blank=True, max_length=20, null=True)),
                ('checkInDate', models.DateField()),
                ('checkInTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('6_months', '6 Months'), ('12_months', '12 Months')], max_length=20)),
                ('start_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
