# Generated by Django 5.1.4 on 2025-01-20 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraService', models.CharField(choices=[('dry_cleaning', 'Dry Cleaning'), ('ironing', 'Ironing'), ('folding', 'Folding')], max_length=20)),
                ('clothesCount', models.PositiveIntegerField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentType', models.CharField(choices=[('online', 'Online'), ('card', 'Card'), ('cash', 'Cash')], max_length=10)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('inquiry', 'Inquiry'), ('appreciation', 'Appreciation')], max_length=20)),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='laundry_Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('ONLINE', 'Online'), ('CASH', 'Cash'), ('CARD', 'Card')], max_length=10)),
                ('payment_for', models.CharField(choices=[('ORDERS', 'Laundry Orders'), ('SERVICES', 'Extra Services')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='laundry_Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('6M', '6 Months'), ('12M', '12 Months')], max_length=3)),
                ('start_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuswashapp.laundry_payments', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryOrders',
            fields=[
                ('laundry_id', models.AutoField(primary_key=True, serialize=False)),
                ('clothes_count', models.PositiveIntegerField()),
                ('extra_item', models.TextField(blank=True, null=True)),
                ('check_in_date', models.DateField(auto_now_add=True)),
                ('check_in_time', models.TimeField(auto_now_add=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Done', 'Not Done'), ('Done', 'Done')], default='Not Done', max_length=10)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuswashapp.laundry_membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
